<template>
  <div
    class="flex items-center justify-center py-8 bg-gradient-to-r from-red-500 via-pink-500 to-yellow-500"
  >
    <div class="font-light text-center text-white">
      Created by
      <a
        class="underline"
        href="https://twitter.com/consolelogjordi"
        target="_blank"
        rel="noreferrer"
      >
        jordihales
      </a>
      and
      <a
        class="underline"
        href="https://twitter.com/itsmarkmead"
        target="_blank"
        rel="noreferrer"
        >markmead</a
      >
      using
      <a
        class="underline"
        href="https://tailwindcss.com/"
        target="_blank"
        rel="noreferrer"
        >Tailwind</a
      >
      and
      <a
        class="underline"
        href="https://vuejs.org/"
        target="_blank"
        rel="noreferrer"
        >Vue</a
      >
    </div>
  </div>
</template>